spring.application.name=list
<<<<<<< HEAD
=======
spring.jpa.hibernate.ddl-auto= update
spring.datasource.url=jdbc:mysql://localhost:3306/todolistnew
spring.datasource.username=root
spring.datasource.password=root

>>>>>>> db3f86d (AGORA COM COMENTARIO AEEEE)
